name: Release Obsidian plugin

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: Build plugin
        run: |
          npm install
          npm run build

      - name: Generate release notes from changelog
        id: notes
        run: |
          node ./getChangelogEntry.mjs > RELEASE_NOTES.md
          echo "file=RELEASE_NOTES.md" >> "$GITHUB_OUTPUT"

      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"

          gh release create "$tag" \
            --title="$tag" \
            --notes-file "${{ steps.notes.outputs.file }}" \
            main.js manifest.json styles.css
